### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by raisiqueira** [eggplanetio/nuxt-cluster#1]
I'm cloning this repo, and run `yarn` on root folder, in the folder `dummy`, i'm run `yarn` and `npm run build`, but return this error:
![image](https://user-images.githubusercontent.com/2914170/28328815-1c23bd5e-6bbe-11e7-9e32-0434ecc52320.png)

**Comment by pimlie** [comment]
I had this problem with the docker-nuxt image and it was because the `srcDir` option was used while it should have been `rootDir`. Thats one of the things I fixed in #2
